# Generated by Django 2.0.1 on 2020-07-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
