# Generated by Django 2.0 on 2020-07-22 03:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('home', '主页'), ('crawl', '爬虫'), ('Algorithmic', '算法'), ('html', '前端'), ('Django', 'Django'), ('school', '大学'), ('travel', '旅游'), ('pets', '宠物'), ('lover', '爱情')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('text', ckeditor.fields.RichTextField(verbose_name='博客内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
