# Generated by Django 2.0 on 2020-07-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_pro',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='user_pro',
            old_name='Head_icon',
            new_name='head_icon',
        ),
        migrations.RenameField(
            model_name='user_pro',
            old_name='Site',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='user_pro',
            old_name='ToUser',
            new_name='to_user',
        ),
    ]
