# Generated by Django 2.0.1 on 2020-07-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200718_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='classification',
            field=models.CharField(choices=[('home', '主页'), ('crawl', '爬虫'), ('Algorithmic', '算法'), ('html', '前端'), ('Django', 'Django'), ('school', '大学'), ('travel', '旅游'), ('pets', '宠物'), ('lover', '爱情')], max_length=50),
        ),
    ]
